
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("Travels.Resource", IsApplication=true)>]
    do ()

namespace Travels
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptione80691bc15734878b3d52a707b5c3f91 of obj
    exception ReturnNoneExceptione80691bc15734878b3d52a707b5c3f91
    [<AutoOpen>]
    module FuncConvertFinalOverloade80691bc15734878b3d52a707b5c3f91 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                global.Xamarin.Android.NUnitLite.Resource.Id.OptionHostName <- Resource_Id.OptionHostName
                global.Xamarin.Android.NUnitLite.Resource.Id.OptionPort <- Resource_Id.OptionPort
                global.Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer <- Resource_Id.OptionRemoteServer
                global.Xamarin.Android.NUnitLite.Resource.Id.OptionsButton <- Resource_Id.OptionsButton
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultFullName <- Resource_Id.ResultFullName
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultMessage <- Resource_Id.ResultMessage
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultResultState <- Resource_Id.ResultResultState
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest <- Resource_Id.ResultRunSingleMethodTest
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace <- Resource_Id.ResultStackTrace
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed <- Resource_Id.ResultsFailed
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultsId <- Resource_Id.ResultsId
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored <- Resource_Id.ResultsIgnored
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive <- Resource_Id.ResultsInconclusive
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage <- Resource_Id.ResultsMessage
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed <- Resource_Id.ResultsPassed
                global.Xamarin.Android.NUnitLite.Resource.Id.ResultsResult <- Resource_Id.ResultsResult
                global.Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton <- Resource_Id.RunTestsButton
                global.Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView <- Resource_Id.TestSuiteListView
                global.Xamarin.Android.NUnitLite.Resource.Layout.options <- Resource_Layout.options
                global.Xamarin.Android.NUnitLite.Resource.Layout.results <- Resource_Layout.results
                global.Xamarin.Android.NUnitLite.Resource.Layout.test_result <- Resource_Layout.test_result
                global.Xamarin.Android.NUnitLite.Resource.Layout.test_suite <- Resource_Layout.test_suite


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member chart = 2130837504
            
            // aapt resource value: 0x7f020001
            static member expenses = 2130837505
            
            // aapt resource value: 0x7f020002
            static member Icon = 2130837506
            
            // aapt resource value: 0x7f020003
            static member money = 2130837507
            
            // aapt resource value: 0x7f020004
            static member monoandroidsplash = 2130837508
            
            // aapt resource value: 0x7f020005
            static member people = 2130837509
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f060006
            static member AddExpenseButton = 2131099654
            
            // aapt resource value: 0x7f06000b
            static member AddPersonButton = 2131099659
            
            // aapt resource value: 0x7f060008
            static member AddPersonLayout = 2131099656
            
            // aapt resource value: 0x7f060001
            static member ChargeAmountLayout = 2131099649
            
            // aapt resource value: 0x7f06000d
            static member OptionHostName = 2131099661
            
            // aapt resource value: 0x7f06000e
            static member OptionPort = 2131099662
            
            // aapt resource value: 0x7f06000c
            static member OptionRemoteServer = 2131099660
            
            // aapt resource value: 0x7f06001d
            static member OptionsButton = 2131099677
            
            // aapt resource value: 0x7f060005
            static member PersonTable = 2131099653
            
            // aapt resource value: 0x7f060018
            static member ResultFullName = 2131099672
            
            // aapt resource value: 0x7f06001a
            static member ResultMessage = 2131099674
            
            // aapt resource value: 0x7f060019
            static member ResultResultState = 2131099673
            
            // aapt resource value: 0x7f060017
            static member ResultRunSingleMethodTest = 2131099671
            
            // aapt resource value: 0x7f06001b
            static member ResultStackTrace = 2131099675
            
            // aapt resource value: 0x7f060013
            static member ResultsFailed = 2131099667
            
            // aapt resource value: 0x7f060010
            static member ResultsId = 2131099664
            
            // aapt resource value: 0x7f060014
            static member ResultsIgnored = 2131099668
            
            // aapt resource value: 0x7f060015
            static member ResultsInconclusive = 2131099669
            
            // aapt resource value: 0x7f060016
            static member ResultsMessage = 2131099670
            
            // aapt resource value: 0x7f060012
            static member ResultsPassed = 2131099666
            
            // aapt resource value: 0x7f060011
            static member ResultsResult = 2131099665
            
            // aapt resource value: 0x7f06001c
            static member RunTestsButton = 2131099676
            
            // aapt resource value: 0x7f06001e
            static member TestSuiteListView = 2131099678
            
            // aapt resource value: 0x7f060003
            static member TextAmountCharge = 2131099651
            
            // aapt resource value: 0x7f060009
            static member TextEmail = 2131099657
            
            // aapt resource value: 0x7f06000a
            static member TextName = 2131099658
            
            // aapt resource value: 0x7f060000
            static member linearLayout1 = 2131099648
            
            // aapt resource value: 0x7f06000f
            static member switch1 = 2131099663
            
            // aapt resource value: 0x7f060002
            static member tableRow4 = 2131099650
            
            // aapt resource value: 0x7f060007
            static member textView1 = 2131099655
            
            // aapt resource value: 0x7f060004
            static member textView12 = 2131099652
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member AddCharge = 2130903040
            
            // aapt resource value: 0x7f030001
            static member AddPerson = 2130903041
            
            // aapt resource value: 0x7f030002
            static member options = 2130903042
            
            // aapt resource value: 0x7f030003
            static member PersonsLayout = 2130903043
            
            // aapt resource value: 0x7f030004
            static member ResultLayout = 2130903044
            
            // aapt resource value: 0x7f030005
            static member results = 2130903045
            
            // aapt resource value: 0x7f030006
            static member test_result = 2130903046
            
            // aapt resource value: 0x7f030007
            static member test_suite = 2130903047
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040001
            static member app_name = 2130968577
            
            // aapt resource value: 0x7f040000
            static member hello = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Style () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050000
            static member Mono_Android_Theme_Splash = 2131034112
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

